# Generated by Django 5.2.6 on 2025-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delete_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
