# Generated by Django 5.2.6 on 2025-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
