# Generated by Django 5.2.6 on 2025-09-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('tasks', '0002_delete_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tasks.task'),
        ),
    ]
